# Load all files

In [20]:
import os
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

organization_path = "data/Organization.xlsx"
marketbucks_path = "data/marketbucksUsage.xlsx"
call_path = "data/Incoming Call.xlsx"
food_path = "data/org_FSStats.xlsx"

organization_records = pd.read_excel(organization_path)
marketbucks_participation = pd.read_excel(marketbucks_path)
call_center_logs = pd.read_excel(call_path)
food_shelf_activity = pd.read_excel(food_path)

## Row and Column Count

In [21]:
# How many rows and columns in all files
print("Number of rows in Organization:", len(organization_records))
print("Number of columns in Organization:", len(organization_records.columns))
print()
print("Number of rows in marketbucksUsage:", len(marketbucks_participation))
print("Number of columns in marketbucksUsage:", len(marketbucks_participation.columns))
print()
print("Number of rows in Incoming Call:", len(call_center_logs))
print("Number of columns in Incoming Call:", len(call_center_logs.columns))
print()
print("Number of rows in org_FSStats:", len(food_shelf_activity))
print("Number of columns in org_FSStats:", len(food_shelf_activity.columns))

Number of rows in Organization: 1202
Number of columns in Organization: 68

Number of rows in marketbucksUsage: 13573
Number of columns in marketbucksUsage: 19

Number of rows in Incoming Call: 49727
Number of columns in Incoming Call: 31

Number of rows in org_FSStats: 28287
Number of columns in org_FSStats: 58

### Organization Records Table

In [52]:
(organization_records.head())

,__ID,CreateTime,zzCreationTS,zzModificationTS,_id_type,City,State,Zip,MailCity,MailState,MailZip,Eligibility,Conditions,MarketSeasons,zcountDaysOperations,Region,SuperRegion,County,StateDistrict,FederalDistrict,DistrictSection,AgencyType,_id_subtype,AgencySubType,isFoodBank,isAgency,isDistributionSite,HoldsInventoryForOthers,isWebscmShipTo,WebscmShipToName,StateClass,MFS,MCS,cCountSites,isActive,ActiveInactive,InactiveDate,TaxEINVerifiedYN,TaxEINVerifiedDate,TaxEINVerifiedMethod,isTEFAPEligible,isTEFAPEligible_Alert,TefapStatus,TefapActiveDate,TefapInActiveDate,TEFAPElligibilityMeans,SuperShelfStatus,SuperShelfCertDate,_id_Bank,_id_Agency,_id_IfFoodBank,isFindHelpMap,FindHelpMapCategory,_id_findhelpMapCat,z12MoAverage_children,z12MoAverage_Adults,z12MoAverage_Senior,z12MoAverage_Indiv,z12MoAverage_House,z12MoAverage_Pounds,z12MoAverage_LlbsPerPerson,z12MoAverage_PeoplePerHouse,z12MoAverage_TEFAPCases,z12MoAverage_LlbsPerHH,z12MoAverage_Meals,zNameIfActiveBank,block_geoid,is_zip_centroid
0,1.0,System.Byte[],NaN,2026-05-15T19:15:18Z,11.0,Rochester,MN,55904.0,Rochester,MN,55904,NaN,NaN,NaN,7.0,Southern Minnesota,Non-Metro,Olmsted,24.0,1.0,A,Agency or Tribal Nation,NaN,NaN,1.0,1.0,0.0,NaN,1.0,CHANNEL ONE FOOD BANK,0.0,NaN,NaN,2.0,1.0,Active,NaT,NaN,2025-11-01,NaN,1.0,NaN,Active,NaT,NaT,Non-profit tax exempt 501c3,NaN,NaT,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Channel One Regional Food Bank*,2.710900e+14,0.0
1,3.0,System.Byte[],NaN,2026-08-06T10:27:10Z,1.0,Brooklyn Park,MN,55428.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twin Cities 7-Metro,Metro,Hennepin-Suburbs,NaN,NaN,NaN,Food Bank,NaN,NaN,1.0,NaN,0.0,NaN,1.0,Second Harvest Heartland,0.0,NaN,NaN,NaN,1.0,Active,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,3.0,15750.0,3.0,NaN,Food Shelves,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Second Harvest Heartland,2.705303e+14,0.0
2,5.0,System.Byte[],NaN,2026-09-01T02:10:43Z,1.0,East Grand Forks,MN,56721.0,East Grand Forks,MN,56721,NaN,NaN,NaN,NaN,Northern Minnesota,Non-Metro,Polk,1.0,7.0,B,Food Bank,NaN,NaN,1.0,1.0,0.0,NaN,1.0,North Country Food Bank,0.0,NaN,NaN,NaN,1.0,Active,NaT,NaN,NaT,NaN,1.0,NaN,Active,NaT,NaT,Non-profit tax exempt 501c3,NaN,NaT,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530.0,NaN,NaN,North Country Food Bank Inc.,2.711902e+14,0.0
3,6.0,System.Byte[],NaN,2026-09-03T10:32:32Z,1.0,Duluth,MN,55808.0,Duluth,MN,55808,NaN,NaN,NaN,NaN,Northern Minnesota,Non-Metro,Saint Louis,8.0,8.0,B,Food Bank,NaN,NaN,1.0,NaN,0.0,NaN,1.0,Second Harvest Northland,0.0,NaN,NaN,NaN,1.0,Active,NaT,NaN,NaT,NaN,1.0,NaN,Active,NaT,NaT,NaN,NaN,NaT,6.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.0,NaN,NaN,Second Harvest Northland,2.713700e+14,0.0
4,7.0,System.Byte[],NaN,2026-01-07T13:35:05Z,1.0,Fargo,ND,58102.0,Fargo,ND,58102,NaN,NaN,NaN,NaN,Central Minnesota,Non-Metro,Clay,NaN,NaN,NaN,Food Bank,NaN,NaN,1.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Inactive,2026-01-07,NaN,NaT,NaN,1.0,NaN,Active,NaT,NaT,NaN,NaN,NaT,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.801700e+14,0.0

### Marketbucks Participation Table

In [54]:
(marketbucks_participation.head())

    _ID          zzCreationTS zzCreationDate      zzModificationTS  _id_site      Dated  SNAPDistributed  SNAPRedeemed  MBDistributed  MBRedeemed  GiftCerts  RCGiftCertificates  PBDistributed  PBRedeemed  RCMBDistributed  RCMBRedeemed  Customers  Transactions  isLateEntry
0  7621  2022-01-06T12:46:33Z     2022-01-06  2025-12-30T13:52:32Z     14214 2022-01-04             0.00          0.00            0.0         0.0        NaN                 NaN            NaN         NaN              NaN           NaN        0.0           NaN          NaN
1  7622  2022-01-06T12:48:30Z     2022-01-06  2025-12-30T13:52:32Z     14214 2022-01-04            52.61         52.61            8.0         8.0        NaN                 NaN            NaN         NaN              NaN           NaN        0.0           NaN          NaN
2  7623  2022-01-06T12:49:57Z     2022-01-06  2025-12-30T13:52:32Z     14214 2022-01-05           337.72        337.72           85.0        85.0        NaN                 NaN            NaN         NaN              NaN           NaN        3.0           NaN          NaN
3  7624  2022-01-13T10:01:03Z     2022-01-13  2025-12-30T13:52:32Z     14214 2022-01-12            26.74         26.74            7.0         7.0        NaN                 NaN            NaN         NaN              NaN           NaN        1.0           NaN          NaN
4  7628  2022-01-14T09:42:31Z     2022-01-14  2025-12-30T13:52:32Z     14214 2022-01-13            59.09         59.09           50.0        50.0        NaN                 NaN            NaN         NaN              NaN           NaN        6.0           NaN          NaN

### Call Center Logs Table

In [56]:
(call_center_logs.head())

     __ID          zzCreationTS      zzModificationTS zzModificationTSNotServer        zzLastArchived       Date             TimeStamp  CallTime   CallLength   CallMethod Call Answered Call Description BestContactMethod            County                Region  NumberInHouse      PrimaryReasonForCall         SNAP Status BridgeToBenefitsScreen Application Mailed SNAPApplicationhelp  isSNAPRx                        ReferralInfoEntry             Referral Source HowHear FollowUpNeeded  FollowUpNeededDays Follow up Date  isFollowup1Complete FollowupDate2  isFollowup2Complete
0  119284  2024-09-11T13:54:54Z  2026-02-13T12:47:16Z                       NaN  2025-05-19T15:21:57Z 2024-09-11  2024-09-11T13:54:54Z  13:54:54          NaN        Email           NaN        Sent Text               NaN  ( Out of State )  Unknown/Out Of State            4.0  Eligibility Requirements                 NaN                    NaN                NaN                 NaN       NaN                                   UW-211                         NaN     NaN            NaN                 NaN            NaT                  NaN           NaT                  NaN
1  119285  2024-09-11T13:59:17Z  2026-02-13T12:47:16Z                       NaN  2025-09-22T13:41:39Z 2024-09-11  2024-09-11T13:59:17Z  13:59:17          NaN      SNAP Rx           2nd        Sent Text               NaN         Kandiyohi    Southern Minnesota            1.0                   SNAP Rx            Screened                    NaN                NaN                 NaN       1.0  SNAP Info Given\nMNBenefits\nFood Shelf  Southwest State University     NaN          Other                 0.0     2024-09-13                  1.0           NaT                  NaN
2  119286  2024-09-11T14:09:22Z  2026-02-13T12:47:16Z                       NaN  2025-09-22T13:41:39Z 2024-09-11  2024-09-11T14:09:22Z  14:09:22          NaN   Voice Mail           NaN        Sent Text               NaN               NaN                   NaN            1.0                 SUN Bucks                 NaN                    NaN                NaN                 NaN       NaN                        SUN Bucks Hotline                         NaN     NaN            NaN                 NaN            NaT                  NaN           NaT                  NaN
3  119287  2024-09-11T14:07:38Z  2026-02-13T12:47:16Z                       NaN  2025-09-22T13:41:39Z 2024-09-11  2024-09-11T14:07:38Z  14:07:38  1-5 minutes  Chat Ticket           1st              NaN               NaN         (Unknown)  Unknown/Out Of State            1.0                     Other      Not Applicable                     No                 No                 NaN       NaN                                   UW-211                         NaN     NaN            NaN                 NaN            NaT                  NaN           NaT                  NaN
4  119288  2024-09-11T14:09:54Z  2026-02-13T12:47:16Z                       NaN  2025-05-19T15:21:57Z 2024-09-11  2024-09-11T14:09:54Z  14:09:54  1-5 minutes    Live Call           NaN        Sent Text               NaN          Hennepin   Twin Cities 7-Metro            1.0      Case-Specific Issues  Currently Enrolled                    NaN                NaN                 NaN       NaN                            County Office                         NaN     NaN            NaN                 NaN            NaT                  NaN           NaT                  NaN

### Food Shelf Activity Table

In [57]:
(food_shelf_activity.head())

    __ID  _id_site  _Year  _Month DateForSearch          zzCreationTS      zzModificationTS  AdultsReg  ChildrenReg  HouseholdsReg  IndividualsReg  Meals  Misc  People  PoundsReg  SeniorsReg  Snacks  UniqueVisitsReg                County  FederalDistrict  StateDistrict                        FoodBank  ChildrenExtra  ChildrenProduce  ChildrenHoliday  AdultsExtra  AdultsProduce  AdultsHoliday  IndividualsExtra  SeniorsExtra  SeniorsProduce  SeniorsHoliday  IndividualsProduce  IndividualsHoliday  UniqueVisitsExtra  UniqueVisitsProduce  UniqueVisitsHoliday  UniqueVisitsTotal  SeniorsTotal  IndividualsTotal  ChildrenTotal  AdultsTotal  HouseholdsExtra  HouseholdsProduce  HouseholdsHoliday  HouseholdsTotal  PoundsExtra  PoundsProduce  PoundsHoliday  PoundsTotal             AgencyType  _id_bank SuperShelf  _YearMonth  PoundsPerIndiv  IndividualsPerHH  id_agency  PoundsPerHH
0   2753    1254.0   2022       1    2022-01-01  2022-01-10T21:48:14Z  2025-12-30T13:50:18Z     1519.0       1048.0         1027.0          2706.0    NaN   NaN     NaN    41548.0       139.0     NaN              NaN             St. Louis              8.0            7.0        Second Harvest Northland            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN         139.0            2706.0         1048.0       1519.0              NaN                NaN                NaN           1027.0          NaN            NaN            NaN      41548.0  Brick and Mortar Site       6.0        NaN      202201            15.0               3.0        NaN         40.0
1   2762   14434.0   2022       1    2022-01-01  2022-01-10T15:01:29Z  2025-12-30T13:50:18Z       23.0         16.0           17.0            47.0    NaN   NaN     NaN      900.0         8.0     NaN              NaN               Olmsted              1.0           24.0  Channel One Regional Food Bank            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN           8.0              47.0           16.0         23.0              NaN                NaN                NaN             17.0          NaN            NaN            NaN        900.0  Brick and Mortar Site       1.0        NaN      202201            19.0               3.0    14434.0         53.0
2  12862    1069.0   2022       3    2022-03-01  2022-03-02T16:18:49Z  2026-09-02T20:20:24Z      281.0         27.0          220.0           343.0    NaN   NaN     NaN    21345.0        35.0     NaN              NaN  Hennepin-Minneapolis              5.0           62.0                  The Food Group            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN          35.0             343.0           27.0        281.0              NaN                NaN                NaN            220.0          NaN            NaN            NaN      21345.0             Food Shelf   14179.0        NaN      202203            62.0               2.0    16988.0         97.0
3  12863    1069.0   2022       1    2022-01-01  2022-03-08T09:50:31Z  2026-09-02T20:20:24Z      281.0         21.0          216.0           330.0    NaN   NaN     NaN    15684.0        28.0     NaN              NaN  Hennepin-Minneapolis              5.0           62.0                  The Food Group            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN          28.0             330.0           21.0        281.0              NaN                NaN                NaN            216.0          NaN            NaN            NaN      15684.0             Food Shelf   14179.0        NaN      202201            48.0               2.0    16988.0         73.0
4  12864   14680.1   2022       1    2022-01-01  2022-03-08T09:50:31Z  2025-12-30T13:50:24Z      142.0         93.0           91.0           266.0    NaN   NaN     NaN     5761.0        31.0     NaN              NaN           Koochiching              8.0            3.0                  The Food Group            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN          31.0             266.0           93.0        142.0              NaN                NaN                NaN             91.0          NaN            NaN            NaN       5761.0         Tribal Program   14179.0        NaN      202201            22.0               3.0        NaN         63.0

## EDA

### Organization Records EDA

In [71]:
print(organization_records.info())
print("\nFirst 3 rows of data:")
print(organization_records.head(3))
print("\nSummary Statistics:")
print(organization_records.describe())
print("\nMissing Cells per Column:")
print(organization_records.isnull().sum())
print(f"\nDuplicate Organization Rows: {organization_records.duplicated().sum()}")

<class 'pandas.DataFrame'>
RangeIndex: 1202 entries, 0 to 1201
Data columns (total 68 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   __ID                         1202 non-null   float64
 1   CreateTime                   788 non-null    str
 2   zzCreationTS                 626 non-null    str
 3   zzModificationTS             1202 non-null   str
 4   _id_type                     1169 non-null   float64
 5   City                         1061 non-null   str
 6   State                        1062 non-null   object
 7   Zip                          1054 non-null   float64
 8   MailCity                     909 non-null    str
 9   MailState                    909 non-null    str
 10  MailZip                      909 non-null    object
 11  Eligibility                  19 non-null     str
 12  Conditions                   19 non-null     str
 13  MarketSeasons                60 non-null     str
 14  zcountDaysOperations         564 non-null    float64
 15  Region                       1125 non-null   str
 16  SuperRegion                  1125 non-null   str
 17  County                       1140 non-null   str
 18  StateDistrict                778 non-null    float64
 19  FederalDistrict              807 non-null    float64
 20  DistrictSection              778 non-null    object
 21  AgencyType                   1169 non-null   str
 22  _id_subtype                  64 non-null     float64
 23  AgencySubType                65 non-null     str
 24  isFoodBank                   6 non-null      float64
 25  isAgency                     329 non-null    float64
 26  isDistributionSite           1179 non-null   float64
 27  HoldsInventoryForOthers      13 non-null     float64
 28  isWebscmShipTo               5 non-null      float64
 29  WebscmShipToName             5 non-null      str
 30  StateClass                   788 non-null    float64
 31  MFS                          8 non-null      float64
 32  MCS                          8 non-null      float64
 33  cCountSites                  1058 non-null   float64
 34  isActive                     1073 non-null   float64
 35  ActiveInactive               1194 non-null   str
 36  InactiveDate                 74 non-null     datetime64[us]
 37  TaxEINVerifiedYN             24 non-null     str
 38  TaxEINVerifiedDate           23 non-null     datetime64[us]
 39  TaxEINVerifiedMethod         24 non-null     str
 40  isTEFAPEligible              717 non-null    float64
 41  isTEFAPEligible_Alert        1 non-null      float64
 42  TefapStatus                  835 non-null    str
 43  TefapActiveDate              27 non-null     datetime64[us]
 44  TefapInActiveDate            11 non-null     datetime64[us]
 45  TEFAPElligibilityMeans       764 non-null    str
 46  SuperShelfStatus             84 non-null     object
 47  SuperShelfCertDate           63 non-null     datetime64[us]
 48  _id_Bank                     947 non-null    float64
 49  _id_Agency                   636 non-null    float64
 50  _id_IfFoodBank               5 non-null      float64
 51  isFindHelpMap                646 non-null    float64
 52  FindHelpMapCategory          514 non-null    str
 53  _id_findhelpMapCat           514 non-null    float64
 54  z12MoAverage_children        588 non-null    float64
 55  z12MoAverage_Adults          587 non-null    float64
 56  z12MoAverage_Senior          580 non-null    float64
 57  z12MoAverage_Indiv           591 non-null    float64
 58  z12MoAverage_House           581 non-null    float64
 59  z12MoAverage_Pounds          586 non-null    float64
 60  z12MoAverage_LlbsPerPerson   557 non-null    float64
 61  z12MoAverage_PeoplePerHouse  550 non-null    float64
 62  z12MoAverage_TEFAPCases      613 non-null    float64
 63  z12MoAverage_LlbsPerHH       550 non-null    float64
 64  z12MoAverage_Meals           393 non-null    float64
 65  zNameIfActiveBank            5 non-null      str
 66  block_geoid                  1052 non-null   float64
 67  is_zip_centroid              1052 non-null   float64
dtypes: datetime64[us](5), float64(37), object(4), str(22)
memory usage: 638.7+ KB
None

First 3 rows of data:
   __ID     CreateTime zzCreationTS      zzModificationTS  _id_type              City State      Zip          MailCity MailState MailZip Eligibility Conditions MarketSeasons  zcountDaysOperations               Region SuperRegion            County  StateDistrict  FederalDistrict DistrictSection               AgencyType  _id_subtype AgencySubType  isFoodBank  isAgency  isDistributionSite  HoldsInventoryForOthers  isWebscmShipTo          WebscmShipToName  StateClass  MFS  MCS  cCountSites  isActive ActiveInactive InactiveDate TaxEINVerifiedYN TaxEINVerifiedDate TaxEINVerifiedMethod  isTEFAPEligible  isTEFAPEligible_Alert TefapStatus TefapActiveDate TefapInActiveDate       TEFAPElligibilityMeans SuperShelfStatus SuperShelfCertDate  _id_Bank  _id_Agency  _id_IfFoodBank  isFindHelpMap FindHelpMapCategory  _id_findhelpMapCat  z12MoAverage_children  z12MoAverage_Adults  z12MoAverage_Senior  z12MoAverage_Indiv  z12MoAverage_House  z12MoAverage_Pounds  z12MoAverage_LlbsPerPerson  \
0   1.0  System.Byte[]          NaN  2026-05-15T19:15:18Z      11.0         Rochester    MN  55904.0         Rochester        MN   55904         NaN        NaN           NaN                   7.0   Southern Minnesota   Non-Metro           Olmsted           24.0              1.0               A  Agency or Tribal Nation          NaN           NaN         1.0       1.0                 0.0                      NaN             1.0     CHANNEL ONE FOOD BANK         0.0  NaN  NaN          2.0       1.0         Active          NaT              NaN         2025-11-01                  NaN              1.0                    NaN      Active             NaT               NaT  Non-profit tax exempt 501c3              NaN                NaT       1.0         1.0             1.0            NaN                 NaN                 NaN                    NaN                  NaN                  NaN                 NaN                 NaN                  NaN                         NaN
1   3.0  System.Byte[]          NaN  2026-08-06T10:27:10Z       1.0     Brooklyn Park    MN  55428.0               NaN       NaN     NaN         NaN        NaN           NaN                   NaN  Twin Cities 7-Metro       Metro  Hennepin-Suburbs            NaN              NaN             NaN                Food Bank          NaN           NaN         1.0       NaN                 0.0                      NaN             1.0  Second Harvest Heartland         0.0  NaN  NaN          NaN       1.0         Active          NaT              NaN                NaT                  NaN              NaN                    NaN         NaN             NaT               NaT                          NaN              NaN                NaT       3.0     15750.0             3.0            NaN        Food Shelves                20.0                    NaN                  NaN                  NaN                 NaN                 NaN                  NaN                         NaN
2   5.0  System.Byte[]          NaN  2026-09-01T02:10:43Z       1.0  East Grand Forks    MN  56721.0  East Grand Forks        MN   56721         NaN        NaN           NaN                   NaN   Northern Minnesota   Non-Metro              Polk            1.0              7.0               B                Food Bank          NaN           NaN         1.0       1.0                 0.0                      NaN             1.0   North Country Food Bank         0.0  NaN  NaN          NaN       1.0         Active          NaT              NaN                NaT                  NaN              1.0                    NaN      Active             NaT               NaT  Non-profit tax exempt 501c3              NaN                NaT       5.0         5.0             5.0            NaN                 NaN                 NaN                    NaN                  NaN                  NaN                 NaN                 NaN                  NaN                         NaN

   z12MoAverage_PeoplePerHouse  z12MoAverage_TEFAPCases  z12MoAverage_LlbsPerHH  z12MoAverage_Meals                zNameIfActiveBank   block_geoid  is_zip_centroid
0                          NaN                      NaN                     NaN                 NaN  Channel One Regional Food Bank*  2.710900e+14              0.0
1                          NaN                      NaN                     NaN                 NaN         Second Harvest Heartland  2.705303e+14              0.0
2                          NaN                    530.0                     NaN                 NaN     North Country Food Bank Inc.  2.711902e+14              0.0

Summary Statistics:
               __ID     _id_type           Zip  zcountDaysOperations  StateDistrict  FederalDistrict  _id_subtype  isFoodBank  isAgency  isDistributionSite  HoldsInventoryForOthers  isWebscmShipTo  StateClass  MFS  MCS  cCountSites  isActive                InactiveDate          TaxEINVerifiedDate  isTEFAPEligible  isTEFAPEligible_Alert      TefapActiveDate           TefapInActiveDate          SuperShelfCertDate      _id_Bank    _id_Agency  _id_IfFoodBank  isFindHelpMap  _id_findhelpMapCat  z12MoAverage_children  z12MoAverage_Adults  z12MoAverage_Senior  z12MoAverage_Indiv  z12MoAverage_House  z12MoAverage_Pounds  z12MoAverage_LlbsPerPerson  z12MoAverage_PeoplePerHouse  z12MoAverage_TEFAPCases  z12MoAverage_LlbsPerHH  z12MoAverage_Meals   block_geoid  is_zip_centroid
count   1202.000000  1169.000000  1.054000e+03            564.000000     778.000000       807.000000     64.00000         6.0     329.0         1179.000000                     13.0             5.0  788.000000  8.0  8.0  1058.000000    1073.0                          74                          23            717.0                    1.0                   27                          11                          63    947.000000    636.000000         5.00000          646.0          514.000000             588.000000           587.000000           580.000000          591.000000          581.000000           586.000000                  557.000000                   550.000000               613.000000              550.000000          393.000000  1.052000e+03      1052.000000
mean   12729.331364     4.978614  4.791215e+06              6.890071      27.557841         5.229244      3.15625         1.0       1.0            0.726887                      0.0             1.0    0.750000  0.0  0.0     1.131380       1.0  2025-05-16 15:14:35.675675  2025-12-07 16:41:44.347826              1.0                    1.0  2025-06-25 16:53:20  2025-08-01 21:49:05.454545  2024-05-10 03:48:34.285714   2638.181626  15957.888365      2838.80000            1.0           20.731518             533.261905           803.402044           178.060345         1502.590525          517.129088         25082.655290                   21.308797                     2.878182                98.078303               57.727273          899.684478  2.709010e+14         0.011407
min        1.000000     0.000000  5.500600e+04              1.000000       1.000000         1.000000      3.00000         1.0       1.0            0.000000                      0.0             1.0    0.000000  0.0  0.0     1.000000       1.0         2022-04-30 00:00:00         2025-10-30 00:00:00              1.0                    1.0  2019-09-01 00:00:00         2023-08-01 00:00:00         2024-05-06 00:00:00     -1.000000      1.000000         1.00000            1.0           20.000000               0.000000             0.000000             0.000000            0.000000            0.000000             0.000000                    0.000000                     0.000000                 0.000000                0.000000            0.000000  2.700177e+14         0.000000
25%    14115.250000     0.000000  5.536900e+04              7.000000       7.250000         4.000000      3.00000         1.0       1.0            0.000000                      0.0             1.0    0.000000  0.0  0.0     1.000000       1.0         2024-11-28 06:00:00         2025-11-13 00:00:00              1.0                    1.0  2025-08-20 12:00:00         2024-12-23 00:00:00         2024-05-10 00:00:00      3.000000  15843.000000         3.00000            1.0           20.000000              30.000000            63.500000            20.000000          122.500000           55.000000          2266.500000                   14.000000                     2.000000                14.000000               37.000000            0.000000  2.704596e+14         0.000000
50%    14732.500000     4.000000  5.574800e+04              7.000000      21.000000         6.000000      3.00000         1.0       1.0            1.000000                      0.0             1.0    1.000000  0.0  0.0     1.000000       1.0         2025-08-22 00:00:00         2025-11-13 00:00:00              1.0                    1.0  2025-09-23 00:00:00         2025-12-15 00:00:00         2024-05-10 00:00:00      3.000000  16272.500000         5.00000            1.0           20.000000             116.500000           210.000000            56.500000          400.000000          151.000000          6889.000000                   20.000000                     3.000000                33.000000               53.000000            0.000000  2.706148e+14         0.000000
75%    16487.500000    11.000000  5.632900e+04              7.000000      48.000000         7.000000      3.00000         1.0       1.0            1.000000                      0.0             1.0    1.000000  0.0  0.0     1.000000       1.0         2025-11-17 00:00:00         2025-11-17 00:00:00              1.0                    1.0  2025-11-05 12:00:00         2026-07-01 00:00:00         2024-05-10 00:00:00      6.000000  16768.250000         6.00000            1.0           20.000000             417.750000           708.500000           168.250000         1276.000000          459.000000         24362.750000                   27.000000                     3.000000                89.000000               72.000000            0.000000  2.712304e+14         0.000000
max    16989.000000    12.000000  5.634203e+08              8.000000      67.000000         8.000000     13.00000         1.0       1.0            1.000000                      0.0             1.0    2.000000  0.0  0.0    26.000000       1.0         2026-09-01 00:00:00         2026-05-20 00:00:00              1.0                    1.0  2026-04-08 00:00:00         2026-07-31 00:00:00         2024-05-17 00:00:00  14179.000000  16988.000000     14179.00000            1.0           24.000000           20134.000000         26685.000000          5472.000000        49853.000000        12973.000000        490057.000000                  143.000000                    11.000000              2777.000000              274.000000        58792.000000  3.801700e+14         1.000000
std     5667.699251     4.918903  5.105262e+07              0.805382      21.955785         2.434907      1.25000         0.0       0.0            0.445747                      0.0             0.0    0.567827  0.0  0.0     1.290654       0.0                         NaN                         NaN              0.0                    NaN                  NaN                         NaN                         NaN   5516.900968   2428.763398      6339.36481            0.0            1.447556            1427.160388          2053.816200           411.215144         3805.276107         1181.573433         51089.158513                   12.417562                     1.051357               223.922745               31.047619         4413.697152  3.407277e+12         0.106242

Missing Cells per Column:
__ID                         0
CreateTime                 414
zzCreationTS               576
zzModificationTS             0
_id_type                    33
                          ...
z12MoAverage_LlbsPerHH     652
z12MoAverage_Meals         809
zNameIfActiveBank         1197
block_geoid                150
is_zip_centroid            150
Length: 68, dtype: int64

Duplicate Organization Rows: 0

### Food Shelf Activity EDA

In [72]:
print(food_shelf_activity.info())
print("\nFirst 3 rows of data:")
print(food_shelf_activity.head(3))
print("\nSummary Statistics:")
print(food_shelf_activity.describe())
print("\nMissing Cells per Column:")
print(food_shelf_activity.isnull().sum())
print(f"\nDuplicate Food Shelf Activity Rows: {food_shelf_activity.duplicated().sum()}")

<class 'pandas.DataFrame'>
RangeIndex: 28287 entries, 0 to 28286
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   __ID                 28287 non-null  int64
 1   _id_site             28287 non-null  float64
 2   _Year                28287 non-null  int64
 3   _Month               28287 non-null  int64
 4   DateForSearch        28287 non-null  datetime64[us]
 5   zzCreationTS         28287 non-null  str
 6   zzModificationTS     28287 non-null  str
 7   AdultsReg            26225 non-null  float64
 8   ChildrenReg          26101 non-null  float64
 9   HouseholdsReg        26049 non-null  float64
 10  IndividualsReg       26260 non-null  float64
 11  Meals                12806 non-null  float64
 12  Misc                 0 non-null      float64
 13  People               0 non-null      float64
 14  PoundsReg            26052 non-null  float64
 15  SeniorsReg           26051 non-null  float64
 16  Snacks               0 non-null      float64
 17  UniqueVisitsReg      19 non-null     float64
 18  County               28155 non-null  str
 19  FederalDistrict      27928 non-null  float64
 20  StateDistrict        27771 non-null  float64
 21  FoodBank             28251 non-null  str
 22  ChildrenExtra        0 non-null      float64
 23  ChildrenProduce      0 non-null      float64
 24  ChildrenHoliday      0 non-null      float64
 25  AdultsExtra          0 non-null      float64
 26  AdultsProduce        0 non-null      float64
 27  AdultsHoliday        0 non-null      float64
 28  IndividualsExtra     0 non-null      float64
 29  SeniorsExtra         0 non-null      float64
 30  SeniorsProduce       0 non-null      float64
 31  SeniorsHoliday       0 non-null      float64
 32  IndividualsProduce   0 non-null      float64
 33  IndividualsHoliday   0 non-null      float64
 34  UniqueVisitsExtra    0 non-null      float64
 35  UniqueVisitsProduce  0 non-null      float64
 36  UniqueVisitsHoliday  0 non-null      float64
 37  UniqueVisitsTotal    19 non-null     float64
 38  SeniorsTotal         26052 non-null  float64
 39  IndividualsTotal     26260 non-null  float64
 40  ChildrenTotal        26102 non-null  float64
 41  AdultsTotal          26225 non-null  float64
 42  HouseholdsExtra      0 non-null      float64
 43  HouseholdsProduce    0 non-null      float64
 44  HouseholdsHoliday    0 non-null      float64
 45  HouseholdsTotal      26049 non-null  float64
 46  PoundsExtra          0 non-null      float64
 47  PoundsProduce        0 non-null      float64
 48  PoundsHoliday        0 non-null      float64
 49  PoundsTotal          26052 non-null  float64
 50  AgencyType           28149 non-null  str
 51  _id_bank             28250 non-null  float64
 52  SuperShelf           34 non-null     str
 53  _YearMonth           28287 non-null  int64
 54  PoundsPerIndiv       24681 non-null  float64
 55  IndividualsPerHH     24468 non-null  float64
 56  id_agency            21874 non-null  float64
 57  PoundsPerHH          24468 non-null  float64
dtypes: datetime64[us](1), float64(47), int64(4), str(6)
memory usage: 12.5 MB
None

First 3 rows of data:
    __ID  _id_site  _Year  _Month DateForSearch          zzCreationTS      zzModificationTS  AdultsReg  ChildrenReg  HouseholdsReg  IndividualsReg  Meals  Misc  People  PoundsReg  SeniorsReg  Snacks  UniqueVisitsReg                County  FederalDistrict  StateDistrict                        FoodBank  ChildrenExtra  ChildrenProduce  ChildrenHoliday  AdultsExtra  AdultsProduce  AdultsHoliday  IndividualsExtra  SeniorsExtra  SeniorsProduce  SeniorsHoliday  IndividualsProduce  IndividualsHoliday  UniqueVisitsExtra  UniqueVisitsProduce  UniqueVisitsHoliday  UniqueVisitsTotal  SeniorsTotal  IndividualsTotal  ChildrenTotal  AdultsTotal  HouseholdsExtra  HouseholdsProduce  HouseholdsHoliday  HouseholdsTotal  PoundsExtra  PoundsProduce  PoundsHoliday  PoundsTotal             AgencyType  _id_bank SuperShelf  _YearMonth  PoundsPerIndiv  IndividualsPerHH  id_agency  PoundsPerHH
0   2753    1254.0   2022       1    2022-01-01  2022-01-10T21:48:14Z  2025-12-30T13:50:18Z     1519.0       1048.0         1027.0          2706.0    NaN   NaN     NaN    41548.0       139.0     NaN              NaN             St. Louis              8.0            7.0        Second Harvest Northland            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN         139.0            2706.0         1048.0       1519.0              NaN                NaN                NaN           1027.0          NaN            NaN            NaN      41548.0  Brick and Mortar Site       6.0        NaN      202201            15.0               3.0        NaN         40.0
1   2762   14434.0   2022       1    2022-01-01  2022-01-10T15:01:29Z  2025-12-30T13:50:18Z       23.0         16.0           17.0            47.0    NaN   NaN     NaN      900.0         8.0     NaN              NaN               Olmsted              1.0           24.0  Channel One Regional Food Bank            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN           8.0              47.0           16.0         23.0              NaN                NaN                NaN             17.0          NaN            NaN            NaN        900.0  Brick and Mortar Site       1.0        NaN      202201            19.0               3.0    14434.0         53.0
2  12862    1069.0   2022       3    2022-03-01  2022-03-02T16:18:49Z  2026-09-02T20:20:24Z      281.0         27.0          220.0           343.0    NaN   NaN     NaN    21345.0        35.0     NaN              NaN  Hennepin-Minneapolis              5.0           62.0                  The Food Group            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN                NaN          35.0             343.0           27.0        281.0              NaN                NaN                NaN            220.0          NaN            NaN            NaN      21345.0             Food Shelf   14179.0        NaN      202203            62.0               2.0    16988.0         97.0

Summary Statistics:
               __ID      _id_site         _Year        _Month               DateForSearch     AdultsReg   ChildrenReg  HouseholdsReg  IndividualsReg         Meals  Misc  People      PoundsReg    SeniorsReg  Snacks  UniqueVisitsReg  FederalDistrict  StateDistrict  ChildrenExtra  ChildrenProduce  ChildrenHoliday  AdultsExtra  AdultsProduce  AdultsHoliday  IndividualsExtra  SeniorsExtra  SeniorsProduce  SeniorsHoliday  IndividualsProduce  IndividualsHoliday  UniqueVisitsExtra  UniqueVisitsProduce  UniqueVisitsHoliday  UniqueVisitsTotal  SeniorsTotal  IndividualsTotal  ChildrenTotal   AdultsTotal  HouseholdsExtra  HouseholdsProduce  HouseholdsHoliday  HouseholdsTotal  PoundsExtra  PoundsProduce  PoundsHoliday    PoundsTotal      _id_bank     _YearMonth  PoundsPerIndiv  IndividualsPerHH     id_agency   PoundsPerHH
count  28287.000000  28287.000000  28287.000000  28287.000000                       28287  26225.000000  26101.000000   26049.000000    26260.000000  12806.000000   0.0     0.0   26052.000000  26051.000000     0.0        19.000000     27928.000000   27771.000000            0.0              0.0              0.0          0.0            0.0            0.0               0.0           0.0             0.0             0.0                 0.0                 0.0                0.0                  0.0                  0.0          19.000000  26052.000000      26260.000000   26102.000000  26225.000000              0.0                0.0                0.0     26049.000000          0.0            0.0            0.0   26052.000000  28250.000000   28287.000000    24681.000000      24468.000000  21874.000000  24468.000000
mean   27266.155796   8848.539686   2023.807403      6.224167  2024-03-29 07:30:16.226535    747.003661    506.740585     481.798380     1412.105407    823.423571   NaN     NaN   25294.242308    163.728110     NaN        74.052632         5.150924      28.909042            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN          74.052632    163.721826       1412.105407     506.721171    747.003661              NaN                NaN                NaN       481.798380          NaN            NaN            NaN   25294.242308   2743.922938  202386.964436       23.460840          2.849926  11617.906144     62.814206
min     2753.000000   1066.000000   2022.000000      0.000000         2022-01-01 00:00:00      0.000000      0.000000       0.000000        0.000000      0.000000   NaN     NaN   -4415.000000     -2.000000     NaN         0.000000         1.000000       1.000000            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN           0.000000     -2.000000          0.000000       0.000000      0.000000              NaN                NaN                NaN         0.000000          NaN            NaN            NaN   -4415.000000      1.000000  202201.000000      -26.000000          0.000000      1.000000    -47.000000
25%    20180.500000   1239.000000   2023.000000      3.000000         2023-03-01 00:00:00     63.000000     31.000000      53.000000      128.000000      0.000000   NaN     NaN    2623.750000     18.000000     NaN         0.000000         4.000000       8.000000            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN           0.000000     18.000000        128.000000      31.000000     63.000000              NaN                NaN                NaN        53.000000          NaN            NaN            NaN    2623.750000      3.000000  202303.000000       15.000000          2.000000   1351.000000     38.000000
50%    27253.000000  14010.000000   2024.000000      6.000000         2024-04-01 00:00:00    190.000000    115.000000     136.000000      372.000000      0.000000   NaN     NaN    7262.000000     49.000000     NaN         1.000000         5.000000      22.000000            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN           1.000000     49.000000        372.000000     115.000000    190.000000              NaN                NaN                NaN       136.000000          NaN            NaN            NaN    7262.000000      3.000000  202404.000000       21.000000          3.000000  15660.000000     57.000000
75%    34374.500000  14585.000000   2025.000000      9.000000         2025-05-01 00:00:00    626.000000    375.000000     425.000000     1160.000000      0.000000   NaN     NaN   23814.000000    147.000000     NaN        49.000000         7.000000      53.000000            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN          49.000000    147.000000       1160.000000     375.000000    626.000000              NaN                NaN                NaN       425.000000          NaN            NaN            NaN   23814.000000      6.000000  202505.000000       29.000000          3.000000  16196.000000     79.000000
max    41550.000000  16917.000000   2026.000000     15.000000         2026-07-01 00:00:00  49756.000000  36915.000000  273385.000000    89669.000000  70182.000000   NaN     NaN  994394.000000  10065.000000     NaN       436.000000         8.000000      67.000000            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN         436.000000  10065.000000      89669.000000   36915.000000  49756.000000              NaN                NaN                NaN    273385.000000          NaN            NaN            NaN  994394.000000  14179.000000  202607.000000      966.000000        100.000000  16988.000000   2164.000000
std     8237.903133   6531.543368      1.321676      3.418972                         NaN   2081.717549   1502.522883    2113.891098     3947.131759   3216.985162   NaN     NaN   53130.937380    470.195239     NaN       144.737876         2.421222      22.417628            NaN              NaN              NaN          NaN            NaN            NaN               NaN           NaN             NaN             NaN                 NaN                 NaN                NaN                  NaN                  NaN         144.737876    470.187308       3947.131759    1502.497374   2081.717549              NaN                NaN                NaN      2113.891098          NaN            NaN            NaN   53130.937380   5597.837036     131.639754       16.840931          1.474112   6429.390724     46.890347

Missing Cells per Column:
__ID                       0
_id_site                   0
_Year                      0
_Month                     0
DateForSearch              0
zzCreationTS               0
zzModificationTS           0
AdultsReg               2062
ChildrenReg             2186
HouseholdsReg           2238
IndividualsReg          2027
Meals                  15481
Misc                   28287
People                 28287
PoundsReg               2235
SeniorsReg              2236
Snacks                 28287
UniqueVisitsReg        28268
County                   132
FederalDistrict          359
StateDistrict            516
FoodBank                  36
ChildrenExtra          28287
ChildrenProduce        28287
ChildrenHoliday        28287
AdultsExtra            28287
AdultsProduce          28287
AdultsHoliday          28287
IndividualsExtra       28287
SeniorsExtra           28287
SeniorsProduce         28287
SeniorsHoliday         28287
IndividualsProduce     28287
IndividualsHoliday     28287
UniqueVisitsExtra      28287
UniqueVisitsProduce    28287
UniqueVisitsHoliday    28287
UniqueVisitsTotal      28268
SeniorsTotal            2235
IndividualsTotal        2027
ChildrenTotal           2185
AdultsTotal             2062
HouseholdsExtra        28287
HouseholdsProduce      28287
HouseholdsHoliday      28287
HouseholdsTotal         2238
PoundsExtra            28287
PoundsProduce          28287
PoundsHoliday          28287
PoundsTotal             2235
AgencyType               138
_id_bank                  37
SuperShelf             28253
_YearMonth                 0
PoundsPerIndiv          3606
IndividualsPerHH        3819
id_agency               6413
PoundsPerHH             3819
dtype: int64

Duplicate Food Shelf Activity Rows: 0

### Marketbucks Participation EDA

In [73]:
print(marketbucks_participation.info())
print("\nFirst 3 rows of data:")
print(marketbucks_participation.head(3))
print("Summary Statistics:")
print(marketbucks_participation.describe())
print("\nMissing Cells per Column:")
print(marketbucks_participation.isnull().sum())
print(f"\nDuplicate Marketbucks Participation Rows: {marketbucks_participation.duplicated().sum()}")

<class 'pandas.DataFrame'>
RangeIndex: 13573 entries, 0 to 13572
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _ID                 13573 non-null  int64
 1   zzCreationTS        13573 non-null  str
 2   zzCreationDate      13573 non-null  datetime64[us]
 3   zzModificationTS    13573 non-null  str
 4   _id_site            13573 non-null  int64
 5   Dated               13573 non-null  datetime64[us]
 6   SNAPDistributed     12951 non-null  float64
 7   SNAPRedeemed        10363 non-null  float64
 8   MBDistributed       12689 non-null  float64
 9   MBRedeemed          10149 non-null  float64
 10  GiftCerts           5830 non-null   float64
 11  RCGiftCertificates  3931 non-null   float64
 12  PBDistributed       11328 non-null  float64
 13  PBRedeemed          9077 non-null   float64
 14  RCMBDistributed     3915 non-null   float64
 15  RCMBRedeemed        3863 non-null   float64
 16  Customers           10516 non-null  float64
 17  Transactions        12802 non-null  float64
 18  isLateEntry         215 non-null    float64
dtypes: datetime64[us](2), float64(13), int64(2), str(2)
memory usage: 2.0 MB
None

First 3 rows of data:
    _ID          zzCreationTS zzCreationDate      zzModificationTS  _id_site      Dated  SNAPDistributed  SNAPRedeemed  MBDistributed  MBRedeemed  GiftCerts  RCGiftCertificates  PBDistributed  PBRedeemed  RCMBDistributed  RCMBRedeemed  Customers  Transactions  isLateEntry
0  7621  2022-01-06T12:46:33Z     2022-01-06  2025-12-30T13:52:32Z     14214 2022-01-04             0.00          0.00            0.0         0.0        NaN                 NaN            NaN         NaN              NaN           NaN        0.0           NaN          NaN
1  7622  2022-01-06T12:48:30Z     2022-01-06  2025-12-30T13:52:32Z     14214 2022-01-04            52.61         52.61            8.0         8.0        NaN                 NaN            NaN         NaN              NaN           NaN        0.0           NaN          NaN
2  7623  2022-01-06T12:49:57Z     2022-01-06  2025-12-30T13:52:32Z     14214 2022-01-05           337.72        337.72           85.0        85.0        NaN                 NaN            NaN         NaN              NaN           NaN        3.0           NaN          NaN
Summary Statistics:
                _ID              zzCreationDate      _id_site                       Dated  SNAPDistributed  SNAPRedeemed  MBDistributed    MBRedeemed    GiftCerts  RCGiftCertificates  PBDistributed    PBRedeemed  RCMBDistributed  RCMBRedeemed     Customers  Transactions  isLateEntry
count  13573.000000                       13573  13573.000000                       13573     12951.000000  10363.000000   12689.000000  10149.000000  5830.000000         3931.000000   11328.000000   9077.000000      3915.000000   3863.000000  10516.000000  12802.000000        215.0
mean   14541.895528  2024-05-28 02:03:35.899211  14523.765638  2024-05-07 01:33:28.074854       219.580045    237.538782     126.393241    149.840705     0.154202            0.108878     127.181509    143.955174         1.049553      0.906580      2.376189     15.197547          1.0
min     7621.000000         2022-01-06 00:00:00      6.000000         2022-01-01 00:00:00         0.000000      0.000000       0.000000      0.000000     0.000000            0.000000       0.000000      0.000000         0.000000      0.000000      0.000000      0.000000          1.0
25%    11119.000000         2023-06-11 00:00:00  14261.000000         2023-06-03 00:00:00        30.000000     21.000000      20.000000     10.000000     0.000000            0.000000      18.000000      8.000000         0.000000      0.000000      0.000000      2.000000          1.0
50%    14526.000000         2024-07-15 00:00:00  14288.000000         2024-06-26 00:00:00        92.000000     73.000000      50.000000     30.000000     0.000000            0.000000      50.000000     28.000000         0.000000      0.000000      1.000000      7.000000          1.0
75%    17935.000000         2025-08-10 00:00:00  14698.000000         2025-07-12 00:00:00       242.000000    199.000000     140.000000     95.000000     0.000000            0.000000     140.000000     91.000000         0.000000      0.000000      2.000000     17.000000          1.0
max    21798.000000         2026-09-01 00:00:00  16958.000000         2026-07-31 00:00:00     10169.000000  29545.000000   17944.000000  22149.000000    82.000000           24.000000   16091.000000  26441.000000       240.000000    328.000000   1236.000000   1212.000000          1.0
std     3963.104007                         NaN    481.308185                         NaN       476.096849    951.752406     275.435587    753.007890     2.385565            1.054664     276.260487    763.883037        10.134234     10.400442     16.485714     33.132569          0.0

Missing Cells per Column:
_ID                       0
zzCreationTS              0
zzCreationDate            0
zzModificationTS          0
_id_site                  0
Dated                     0
SNAPDistributed         622
SNAPRedeemed           3210
MBDistributed           884
MBRedeemed             3424
GiftCerts              7743
RCGiftCertificates     9642
PBDistributed          2245
PBRedeemed             4496
RCMBDistributed        9658
RCMBRedeemed           9710
Customers              3057
Transactions            771
isLateEntry           13358
dtype: int64

Duplicate Marketbucks Participation Rows: 0

### Call Center Logs EDA

In [74]:
print(call_center_logs.info())
print("\nFirst 3 rows of data:")
print(call_center_logs.head(3))
print("\nSummary Statistics:")
print(call_center_logs.describe())
print("\nMissing Cells per Column:")
print(call_center_logs.isnull().sum())
print(f"\nDuplicate Call Center Logs Rows: {call_center_logs.duplicated().sum()}")

<class 'pandas.DataFrame'>
RangeIndex: 49727 entries, 0 to 49726
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   __ID                       49727 non-null  int64
 1   zzCreationTS               49725 non-null  str
 2   zzModificationTS           49727 non-null  str
 3   zzModificationTSNotServer  7132 non-null   str
 4   zzLastArchived             49727 non-null  str
 5   Date                       49727 non-null  datetime64[us]
 6   TimeStamp                  49727 non-null  str
 7   CallTime                   49202 non-null  object
 8   CallLength                 28223 non-null  str
 9   CallMethod                 49727 non-null  str
 10  Call Answered              27057 non-null  str
 11  Call Description           18782 non-null  str
 12  BestContactMethod          2573 non-null   str
 13  County                     34568 non-null  str
 14  Region                     34397 non-null  str
 15  NumberInHouse              49710 non-null  float64
 16  PrimaryReasonForCall       49634 non-null  str
 17  SNAP Status                34730 non-null  str
 18  BridgeToBenefitsScreen     4837 non-null   str
 19  Application Mailed         5279 non-null   str
 20  SNAPApplicationhelp        25 non-null     str
 21  isSNAPRx                   15565 non-null  float64
 22  ReferralInfoEntry          35114 non-null  str
 23  Referral Source            19192 non-null  str
 24  HowHear                    1075 non-null   str
 25  FollowUpNeeded             14002 non-null  str
 26  FollowUpNeededDays         14002 non-null  float64
 27  Follow up Date             15739 non-null  datetime64[us]
 28  isFollowup1Complete        16670 non-null  float64
 29  FollowupDate2              659 non-null    datetime64[us]
 30  isFollowup2Complete        874 non-null    float64
dtypes: datetime64[us](3), float64(5), int64(1), object(1), str(21)
memory usage: 11.8+ MB
None

First 3 rows of data:
     __ID          zzCreationTS      zzModificationTS zzModificationTSNotServer        zzLastArchived       Date             TimeStamp  CallTime CallLength  CallMethod Call Answered Call Description BestContactMethod            County                Region  NumberInHouse      PrimaryReasonForCall SNAP Status BridgeToBenefitsScreen Application Mailed SNAPApplicationhelp  isSNAPRx                        ReferralInfoEntry             Referral Source HowHear FollowUpNeeded  FollowUpNeededDays Follow up Date  isFollowup1Complete FollowupDate2  isFollowup2Complete
0  119284  2024-09-11T13:54:54Z  2026-02-13T12:47:16Z                       NaN  2025-05-19T15:21:57Z 2024-09-11  2024-09-11T13:54:54Z  13:54:54        NaN       Email           NaN        Sent Text               NaN  ( Out of State )  Unknown/Out Of State            4.0  Eligibility Requirements         NaN                    NaN                NaN                 NaN       NaN                                   UW-211                         NaN     NaN            NaN                 NaN            NaT                  NaN           NaT                  NaN
1  119285  2024-09-11T13:59:17Z  2026-02-13T12:47:16Z                       NaN  2025-09-22T13:41:39Z 2024-09-11  2024-09-11T13:59:17Z  13:59:17        NaN     SNAP Rx           2nd        Sent Text               NaN         Kandiyohi    Southern Minnesota            1.0                   SNAP Rx    Screened                    NaN                NaN                 NaN       1.0  SNAP Info Given\nMNBenefits\nFood Shelf  Southwest State University     NaN          Other                 0.0     2024-09-13                  1.0           NaT                  NaN
2  119286  2024-09-11T14:09:22Z  2026-02-13T12:47:16Z                       NaN  2025-09-22T13:41:39Z 2024-09-11  2024-09-11T14:09:22Z  14:09:22        NaN  Voice Mail           NaN        Sent Text               NaN               NaN                   NaN            1.0                 SUN Bucks         NaN                    NaN                NaN                 NaN       NaN                        SUN Bucks Hotline                         NaN     NaN            NaN                 NaN            NaT                  NaN           NaT                  NaN

Summary Statistics:
                __ID                        Date  NumberInHouse  isSNAPRx  FollowUpNeededDays              Follow up Date  isFollowup1Complete               FollowupDate2  isFollowup2Complete
count   49727.000000                       49727   49710.000000   15565.0        14002.000000                       15739              16670.0                         659                874.0
mean   118269.592917  2024-09-10 10:03:37.909787       1.215429       1.0            0.385945  2025-03-07 23:47:05.973696                  1.0  2023-08-15 03:23:13.019726                  1.0
min     81356.000000         2022-02-23 00:00:00       1.000000       1.0            0.000000         2022-11-18 00:00:00                  1.0         2022-07-15 00:00:00                  1.0
25%    105830.500000         2023-10-12 00:00:00       1.000000       1.0            0.000000         2024-07-17 12:00:00                  1.0         2023-06-02 00:00:00                  1.0
50%    118263.000000         2024-08-21 00:00:00       1.000000       1.0            0.000000         2025-05-01 00:00:00                  1.0         2023-07-31 00:00:00                  1.0
75%    130693.500000         2025-07-23 00:00:00       1.000000       1.0            0.000000         2025-11-21 00:00:00                  1.0         2023-09-28 00:00:00                  1.0
max    143662.000000         2026-07-31 00:00:00      14.000000       1.0           42.000000         2026-08-11 00:00:00                  1.0         2026-05-18 00:00:00                  1.0
std     14386.033796                         NaN       0.766721       0.0            2.434461                         NaN                  0.0                         NaN                  0.0

Missing Cells per Column:
__ID                             0
zzCreationTS                     2
zzModificationTS                 0
zzModificationTSNotServer    42595
zzLastArchived                   0
Date                             0
TimeStamp                        0
CallTime                       525
CallLength                   21504
CallMethod                       0
Call Answered                22670
Call Description             30945
BestContactMethod            47154
County                       15159
Region                       15330
NumberInHouse                   17
PrimaryReasonForCall            93
SNAP Status                  14997
BridgeToBenefitsScreen       44890
Application Mailed           44448
SNAPApplicationhelp          49702
isSNAPRx                     34162
ReferralInfoEntry            14613
Referral Source              30535
HowHear                      48652
FollowUpNeeded               35725
FollowUpNeededDays           35725
Follow up Date               33988
isFollowup1Complete          33057
FollowupDate2                49068
isFollowup2Complete          48853
dtype: int64

Duplicate Call Center Logs Rows: 1